
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis:latest
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
      readOnly: true
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: foo
    emptyDir: {}
  - name: secret-volume
    secret:
      secretName: simple-secret

