
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  volumes:
    - name: html-volume
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
    - name: debian-container
      image: debian
      volumeMounts:
        - name: html-volume
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            date > /html/index.html;
            sleep 1;
          done;

