
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: Always
    env:
    - name: CONFIGMAP_PARAM
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: config-param
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  restartPolicy: Never

